### ISSUE TITLE
Do we want to customize our issue/pull request templates?

### ISSUE THREAD

**Issue by climbfuji** [JCSDA/spack#267]
### Summary

We are using the spack issue templates (and no pull request template) for our spack fork.

This requires no maintenance, but it may not be what we want? Especially the need to check the `ran spack debug report` and `searched spack issues/pull request` boxes.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA @ulmononian Do you have any opinion on this spack question?

**Comment by AlexanderRichert-NOAA** [comment]
I like the checkboxes for the feature request template, I think they're still appropriate/potentially useful info. As for the others, since it'll usually be us filing issues, I don't see any urgent need to change them. The only thing I can think of is that we probably usually won't want to @ package maintainers outside of NOAA/JCSDA/etc. since those should generally go through main Spack anyway.
